@startuml
!define AWS diagrams/AWS/dist
!include AWS/AWSCommon.puml
!include AWS/EndUserComputing/all.puml
!include AWS/Storage/SimpleStorageServiceS3.puml

actor "Person" as personAlias
WorkDocs(desktopAlias, "Label", "Technology", "Optional Description")
SimpleStorageServiceS3(storageAlias, "Label", "Technology", "Optional Description")

personAlias --> desktopAlias
desktopAlias --> storageAlias
@enduml